---
deployment:
  tasks:
    - export PHP_BIN=$(which php8.3 2>/dev/null || which php83 2>/dev/null || which php 2>/dev/null)
    - $PHP_BIN artisan config:clear
    - $PHP_BIN artisan cache:clear
    - $PHP_BIN artisan view:clear
    - $PHP_BIN artisan route:clear
    - $PHP_BIN artisan migrate --force
    - $PHP_BIN artisan storage:link --force
    - $PHP_BIN artisan optimize
