import { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { Bar } from 'react-chartjs-2';
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, Tooltip, Legend } from 'chart.js';
import { useAuth } from '@/context/AuthContext';
import projectFinanceService from '@/services/projectFinanceService';
import projectService from '@/services/projectService';
import LoadingSpinner from '@/components/LoadingSpinner';
import toast from 'react-hot-toast';
import { HiOutlinePlus, HiOutlineTrash, HiOutlinePencil, HiOutlineUpload, HiOutlineDownload } from 'react-icons/hi';

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend);
const labels = { expenses: 'Expenses', 'vendor-payments': 'Vendor Payments', 'subcontractor-claims': 'Subcontractor Claims', budgets: 'Budget' };
const fields = { expenses: [['expense_date','Date','date'],['category','Category','text'],['description','Description','text'],['vendor','Vendor','text'],['invoice_no','Invoice No','text'],['do_no','DO No','text'],['amount','Amount (RM)','number']], budgets: [['month','Month','month'],['category','Category','text'],['budgeted_cost','Budgeted Cost (RM)','number']], 'vendor-payments': [['vendor','Vendor','text'],['invoice_no','Invoice No','text'],['do_no','DO No','text'],['submitted_date','Submitted Date','date'],['paid_date','Paid Date','date'],['amount','Amount (RM)','number']], 'subcontractor-claims': [['subcontractor','Subcontractor','text'],['claim_no','Claim No','text'],['invoice_no','Invoice No','text'],['do_no','DO No','text'],['submitted_date','Submitted Date','date'],['certified_date','Certified Date','date'],['paid_date','Paid Date','date'],['amount','Claim Amount (RM)','number'],['certified_amount','Certified Amount (RM)','number']] };
const initial = (resource) => Object.fromEntries((fields[resource] || []).map(([key]) => [key, '']));
const money = (v) => `RM ${Number(v || 0).toLocaleString('en-MY', { minimumFractionDigits: 2 })}`;

export default function ProjectFinance() {
    const { can } = useAuth(); const canEdit = can('projects.edit'); const { pathname } = useLocation();
    const resource = pathname.split('/').pop(); const report = resource === 'reports'; const title = report ? 'Reports' : labels[resource] || 'Project Finance';
    const [rows, setRows] = useState([]); const [projects, setProjects] = useState([]); const [loading, setLoading] = useState(true); const [filters, setFilters] = useState({ project_id: '', month: '', category: '', vendor: '' }); const [form, setForm] = useState(initial(resource)); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [chartRows, setChartRows] = useState([]);
    const load = useCallback(async () => { setLoading(true); try { if (report) { const r = await projectFinanceService.chart(filters); setChartRows(r.data?.data || r.data || []); } else { const r = await projectFinanceService.list(resource, filters); setRows(r.data?.data || []); } } catch { toast.error('Unable to load project finance records'); } finally { setLoading(false); } }, [resource, report, filters]);
    useEffect(() => { load(); }, [load]); useEffect(() => { projectService.list({ per_page: 100 }).then((r) => setProjects(r.data?.data || [])).catch(() => {}); }, []);
    const setFilter = (key, value) => setFilters((prev) => ({ ...prev, [key]: value }));
    const save = async (event) => { event.preventDefault(); try { const data = { ...form, project_id: form.project_id || filters.project_id }; if (editing) await projectFinanceService.update(resource, editing, data); else await projectFinanceService.create(resource, data); toast.success('Saved'); setShowForm(false); setEditing(null); load(); } catch (e) { toast.error(e.response?.data?.message || 'Unable to save'); } };
    const remove = async (id) => { if (!window.confirm('Delete this record?')) return; try { await projectFinanceService.remove(resource, id); toast.success('Deleted'); load(); } catch { toast.error('Unable to delete'); } };
    const chart = useMemo(() => ({ labels: chartRows.map((r) => r.month), datasets: [{ label: 'Budgeted Cost', data: chartRows.map((r) => r.budgeted_cost), backgroundColor: '#5b8def' }, { label: 'Actual Cost', data: chartRows.map((r) => r.actual_cost), backgroundColor: '#ffbd70' }, { label: 'Certified Claims', data: chartRows.map((r) => r.certified_claims), backgroundColor: '#e85ac5' }] }), [chartRows]);
    const query = Object.fromEntries(Object.entries(filters).filter(([, value]) => value));
    const download = (format) => { window.open(projectFinanceService.exportUrl(resource, query, format), '_blank'); };
    const importFile = async (event) => { const file = event.target.files?.[0]; if (!file || !filters.project_id) { toast.error('Select a project before importing'); return; } try { await projectFinanceService.import(file, filters.project_id, resource); toast.success('Workbook imported'); load(); } catch { toast.error('Import failed'); } event.target.value = ''; };
    if (loading && !rows.length && !chartRows.length) return <LoadingSpinner />;
    return <div>
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-gray-900">Project Finance — {title}</h1><p className="text-sm text-gray-500">Manage project finance records and filtered reporting</p></div>{!report && <div className="flex gap-2">{!['budgets'].includes(resource) && canEdit && <label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-gray-300 px-3 py-2 text-sm font-semibold"><HiOutlineUpload /> Import Excel<input type="file" accept=".xlsx,.xls" className="hidden" onChange={importFile} /></label>}<button onClick={() => { setEditing(null); setForm(initial(resource)); setShowForm(true); }} disabled={!canEdit} className="inline-flex items-center gap-2 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><HiOutlinePlus /> New Record</button></div>}</div>
        <div className="mb-5 grid gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200 sm:grid-cols-4"><select value={filters.project_id} onChange={(e) => setFilter('project_id', e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">All Projects</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="month" value={filters.month} onChange={(e) => setFilter('month', e.target.value)} className="rounded-lg border px-3 py-2 text-sm" />{['expenses','reports'].includes(resource) && <input placeholder="Category" value={filters.category} onChange={(e) => setFilter('category', e.target.value)} className="rounded-lg border px-3 py-2 text-sm" />}{['expenses','vendor-payments','subcontractor-claims','reports'].includes(resource) && <input placeholder="Vendor / Subcontractor" value={filters.vendor} onChange={(e) => setFilter('vendor', e.target.value)} className="rounded-lg border px-3 py-2 text-sm" />}</div>
        {report ? <><div className="mb-3 flex justify-end gap-2"><button onClick={() => download('xlsx')} className="inline-flex items-center gap-1 rounded border px-3 py-1.5 text-sm"><HiOutlineDownload /> Excel</button><button onClick={() => download('pdf')} className="inline-flex items-center gap-1 rounded border px-3 py-1.5 text-sm"><HiOutlineDownload /> PDF</button></div><div className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-gray-200"><div className="mb-4 flex justify-between"><h2 className="font-semibold">Monthly Project Financial Status (RM)</h2><span className="text-xs text-gray-500">Budgeted Cost · Actual Cost · Certified Claims</span></div><Bar data={chart} options={{ responsive: true, scales: { y: { beginAtZero: true, ticks: { callback: (value) => money(value) } } } }} /></div></> : <><div className="mb-3 flex justify-end gap-2"><button onClick={() => download('xlsx')} className="inline-flex items-center gap-1 rounded border px-3 py-1.5 text-sm"><HiOutlineDownload /> Excel</button><button onClick={() => download('pdf')} className="inline-flex items-center gap-1 rounded border px-3 py-1.5 text-sm"><HiOutlineDownload /> PDF</button></div><div className="overflow-x-auto rounded-xl bg-white shadow-sm ring-1 ring-gray-200"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Project</th>{(fields[resource] || []).map(([, label]) => <th key={label} className="px-4 py-3">{label}</th>)}<th className="px-4 py-3">Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t"><td className="px-4 py-3">{row.project?.name || '—'}</td>{(fields[resource] || []).map(([key]) => <td key={key} className="whitespace-nowrap px-4 py-3">{key.includes('amount') || key === 'budgeted_cost' ? money(row[key]) : row[key] || '—'}{key === 'paid_date' && row.payment_timing ? <div className="text-xs text-gray-500">{row.payment_timing}</div> : null}</td>)}<td className="px-4 py-3"><button disabled={!canEdit} onClick={() => { setEditing(row.id); setForm(Object.fromEntries((fields[resource] || []).map(([key]) => [key, row[key] || '']))); setShowForm(true); }} className="mr-2 text-primary-600 disabled:opacity-40"><HiOutlinePencil /></button><button disabled={!canEdit} onClick={() => remove(row.id)} className="text-red-600 disabled:opacity-40"><HiOutlineTrash /></button></td></tr>)}{!rows.length && <tr><td colSpan={(fields[resource]?.length || 1) + 2} className="px-4 py-10 text-center text-gray-500">No records found.</td></tr>}</tbody></table></div></>}
        {showForm && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={save} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl"><h2 className="mb-4 text-lg font-semibold">{editing ? 'Edit' : 'New'} {title}</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Project<select required value={form.project_id || filters.project_id} onChange={(e) => setForm({ ...form, project_id: e.target.value })} className="mt-1 w-full rounded border px-3 py-2"><option value="">Select project</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{(fields[resource] || []).map(([key, label, type]) => <label key={key} className="text-sm">{label}<input required={['expense_date','month'].includes(key)} type={type} value={form[key] || ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full rounded border px-3 py-2" /></label>)}</div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setShowForm(false)} className="rounded border px-4 py-2">Cancel</button><button className="rounded bg-primary-600 px-4 py-2 font-semibold text-white">Save</button></div></form></div>}
    </div>;
}
